---
title: "NK request"
author: "Sung Rye Park"
date: "2023-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, fig.align = "center", message=F, warning=F)
```
## R Markdown
This is the report to respond to the request.

```{r libraries, echo=FALSE}
# Load required libraries
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
```

## comparison of 1000set and 500set HUVEC UP-reg genes
```{r}
up.huvec.1000_110 <- c("IFIH1", "PODXL", "CD93", "NT5E", "HYAL2", "ECE1", 
                       "PLPP3", "USP18", "TRIM25", "ITGA5", "SHISA5", "ADGRL4", 
                       "CALCRL", "TPM4", "PLXND1", "UTRN", "NRP1", "NRP2", 
                       "PCDH17", "SPRY1", "TMSB4X", "S1PR1", "TGM2", "PML", 
                       "ZC3HAV1", "PARP10", "ETS1", "LGALS9", "TGFBR2", "S100A10", 
                       "GMPR", "MMRN2", "SLC15A3", "CDH5", "CNP", "HSPA5", 
                       "STOM", "APP", "CEMIP2", "MALL", "SNRK", "ANPEP", 
                       "MEF2C", "MSN", "ADAMTS1", "ABL2", "RAPGEF5", "NID1", 
                       "LRRC32", "HSBP1", "CTSL", "PLS3", "YME1L1", "KLF6", 
                       "PNP", "WWTR1", "TIE1", "MYH9", "NAMPT", "PECAM1", 
                       "STAT2", "CLIC4", "PRSS23", "MCAM", "NEDD9", "SYNPO", 
                       "C6orf62", "MMP14", "ITGA6", "GOLM1", "IL6ST", "DYNC1LI2", 
                       "SERPINB9", "PDE4B", "ATP2B4", "CD109", "KDR", "ERG", 
                       "PPM1F", "APLNR", "MEF2A", "SHANK3", "LAMC1", "ELK3", 
                       "CTSB", "ADIRF", "PCAT19", "ADAM15", "TSPAN18", "MYD88", 
                       "ADAMTS9", "PRCP", "SELENON", "UBE2J1", "SLC25A37", 
                       "FZD4", "GIMAP6", "NCOA7", "PMP22", "RNASE1", "SLC12A2", 
                       "LYVE1", "APOL1", "FLT1", "SULF2", "MGST2", "STARD4", 
                       "SMAD1", "ADAMTS4", "MYADM")

up.huvec.500_376  <- c("S100A6", "PCDH17", "CD9", "S100A10", "PRSS23", "ADAMTS1", 
                       "PODXL", "USP18", "CD93", "PLPP3", "SERPINE1", "IL1RL1", 
                       "CD59", "IFIH1", "ANPEP", "ADGRL4", "PNP", "RGS5", "HYAL2", 
                       "TGM2", "TMSB4X", "TPM4", "PLS3", "PRSS3", "ECE1", "CAVIN1", 
                       "CLIC4", "NAMPT", "MGP", "HSP90AB1", "RHOC", "FKBP1A", 
                       "MCAM", "TOMM5", "CLIC1", "LGALS9", "TRIM25", "ITGA5", 
                       "ANXA2", "MALL", "PTGS2", "CD99", "SEC61G", "SRI", "FSTL1", 
                       "ARHGDIB", "IL6ST", "CALCRL", "SPOCK1", "SSB", "APLNR", 
                       "TAGLN2", "ZC3HAV1", "SPARC", "PROCR", "HMGA1", "ZNFX1", 
                       "TUBB6", "S1PR1", "C4orf3", "DYNLT1", "RPS17", "SLIRP", 
                       "TUBB", "PSMA6", "LYVE1", "LRRC32", "HSBP1", "MYADM", 
                       "POMP", "NCOA7", "PALM2-AKAP2", "PMP22", "STOM", "FKBP3", 
                       "DUSP23", "TPM3", "HSPA5", "BCAT1", "HNRNPR", "NQO1", 
                       "HMOX1", "NEDD9", "ADIRF", "EBPL", "CAP1", "RTN4", "F2R", 
                       "SH3BGRL3", "ZYX", "GOLM1", "NRP1", "YWHAZ", "C6orf62", 
                       "KHDRBS1", "PDCD5", "PRCP", "RAI14", "TNFSF10", "UPP1", 
                       "NOP10", "EHD4", "CANX", "MICOS10", "HSPD1", "RAN", "TIMM8B", 
                       "PDLIM4", "CALR", "LGALS1", "ECSCR", "GALNT1", "TXNDC17", 
                       "GMPR", "MAP1B", "CALM1", "ENO1", "ACTB", "UBE2J1", "RPL23", 
                       "SERPINB9", "PKM", "GNAI2", "NES", "LDHA", "KDELR2", "SNRPE", 
                       "ITGA6", "CLTC", "SNRPD1", "SRPX", "CD81", "DDX21", "NDUFA12", 
                       "PDIA6", "ESAM", "NHP2", "ATP5MF", "SLK", "NDUFC1", "LMNA", 
                       "MMP14", "GTF2H5", "RAC1", "YWHAE", "RPS27L", "PPIA", "ICAM2", 
                       "CALM3", "ATP5F1B", "ACTR3", "SNX6", "PRDX1", "THBS1", "DSTN", 
                       "CAPZA1", "NME2", "ABL2", "PDLIM5", "CISD1", "RBIS", "HNRNPC", 
                       "SF3B6", "ETS1", "S100A16", "GIMAP6", "CDH5", "MDK", "KPNB1", 
                       "HECW2", "PML", "TUBA1C", "UBE2L3", "TNFRSF1A", "SSR3", 
                       "ATP5F1C", "NID1", "EMP1", "EIF4A1", "MGST1", "MMRN2", "VDAC1", 
                       "KLF6", "PDIA3", "ACLY", "UQCRH", "SCP2", "CAV2", "ATP5MC3", 
                       "BACE2", "PTMS", "LRRC8C", "SNRK", "COX7B", "ANXA5", "EI24", 
                       "ATP5MD", "SET", "TBCA", "MEF2C", "PGAM1", "GNS", "YWHAB", 
                       "UBE2K", "PSMB8", "AIDA", "APP", "PSMA3", "LARS", "CNBP", 
                       "NME1", "TUBA1B", "NR2F2", "MRPL20", "MIF", "CAPNS1", 
                       "CSNK1A1", "DAP", "TMBIM6", "RPS20", "DARS", "ARPC2", "VCL", 
                       "COX8A", "PTGR1", "PKIG", "SGK1", "NDUFA7", "MANF", "PLXND1", 
                       "RWDD1", "CSDE1", "SNRPG", "LGMN", "KRTCAP2", "CNP", 
                       "SYNCRIP", "CAPZA2", "MYL6", "COX16", "GNG10", "ENDOD1", 
                       "APOL1", "GNB4", "GCLM", "SRM", "AHNAK", "EIF2S1", "EIF5A", 
                       "EDN1", "CHURC1", "STARD4", "PPM1F", "TOMM7", "RGCC", 
                       "CTNNA1", "SUB1", "ARPC1B", "GNB2", "CD276", "TMEM219", 
                       "SSR1", "PTGES3", "SELENOW", "PCBP1", "ACVRL1", "PFDN2", 
                       "PSMD1", "MRPL17", "G3BP1", "SYNPO", "TSPAN18", "TALDO1", 
                       "EFHD2", "MYL12B", "LAMTOR2", "APLP2", "ZCRB1", "ARPC3", 
                       "KDR", "MEF2A", "HEBP2", "ATOX1", "PSMB2", "PSMA7", "YWHAH", 
                       "SERBP1", "CAPN2", "MRPS36", "PSMA4", "SEC61A1", "EIF1AX", 
                       "IARS", "EIF4G2", "ACTR2", "RAB11A", "POLR2F", "SULF2", 
                       "SNRPF", "SRSF3", "PTPN14", "NDUFB6", "FLT1", "ENG", "CFL1", 
                       "NAP1L1", "MRPL36", "NRCAM", "SUMO3", "DESI1", "CCT4", 
                       "ASPH", "ERH", "REEP5", "SRP9", "SERPINB1", "PSMB3", 
                       "ANXA1", "SEPTIN2", "MGST3", "PAFAH1B2", "PPIC", "TSPO", 
                       "C1QBP", "PECAM1", "EFR3A", "KCTD12", "ATP5MC1", "COX6A1", 
                       "BOLA3", "ELOC", "MGST2", "BCLAF1", "OAF", "ATG3", "CCT8", 
                       "MRPS18C", "PABPC1", "TMED2", "SNRPB", "SERPINH1", "LAMP2", 
                       "NCL", "ARPC5", "PHB", "TMEM158", "YWHAQ", "GNG12", "CCT3", 
                       "TXNL4A", "RRAS", "CALM2", "CYCS", "NDUFB3", "GDI2", 
                       "JAM3", "GADD45A", "SLC15A3", "CKLF", "TKT", "HEG1", 
                       "RHOA", "STAT2", "ANXA4", "TRAM1", "MPZL2", "DPYSL3", 
                       "PLXNA2", "ZDHHC3", "RAB5C", "RBM3", "LMO7", "SEC61B", 
                       "RNASE1", "TLNRD1", "ARCN1")

ven_list = list('1000set'=up.huvec.1000_110, '500set'=up.huvec.500_376)

## draw venn diagram
ven_out <- VennDetail::venndetail(ven_list)

```

### Genes 
#### top : up.huvec.1000_110   
#### bottom : up.huvec.500_376   

```{r}
print(up.huvec.1000_110)
print(up.huvec.500_376)
```


```{r}
plot(ven_out)
# plot(ven_out, type = "upset")
```

```{r, echo=FALSE}
## generate the shared gene list matrix
df = ven_out@result$Subset %>% table() %>% data.frame()
ven.info = df$. %>% factor() %>% levels() ## types of sharing among groups
df$gene =''
for(i in 1:nrow(df)){
  df[i, ]$gene = ven_out@result[ven_out@result$Subset == ven.info[i], ] %>% 
    dplyr::select(Detail) %>% 
    pull() %>% paste0(collapse = ',')
}
```

```{r}
# DT::datatable(df, options = list(scrollX = TRUE, scrollY = "400px"))
print(df[1,])
print(df[2,])
print(df[3,])
```

